import type { TestPaper } from "@app/types";

/**
 * Phase 2 seed data — mirrors hifi/library.jsx::MOCK_TESTS_HF.
 * Replaced by IndexedDB hydration once real PDFs are uploaded (Phase 2 late).
 */

export const MOCK_TESTS: TestPaper[] = [
  {
    id: "t1",
    title: "2024학년도 6월 모의평가",
    problemCount: 30,
    status: "warn",
    statusText: "검토 중 (3)",
    time: "오늘",
    subject: "공통+미적분",
    tags: ["고3", "모의평가", "6월"],
    grade: "고3",
    topicDistribution: [
      { topic: "다항식", count: 6, accuracy: 88 },
      { topic: "지수·로그", count: 5, accuracy: 72 },
      { topic: "삼각함수", count: 5, accuracy: 65 },
      { topic: "수열", count: 6, accuracy: 80 },
      { topic: "미적분", count: 8, accuracy: 60 },
    ],
    variants: [],
    problems: [],
  },
  {
    id: "t2",
    title: "2023학년도 수능 (홀수형)",
    problemCount: 30,
    status: "ok",
    statusText: "완료",
    time: "어제",
    subject: "공통+미적분",
    tags: ["고3", "수능"],
    grade: "고3",
    topicDistribution: [],
    variants: [
      { id: "v1", createdAt: "2024-01-15", intensity: 1, count: 3, label: "기말 대비 변형" },
    ],
    problems: [],
  },
  {
    id: "t3",
    title: "2학기 중간고사 대비 모의",
    problemCount: 25,
    status: "ok",
    statusText: "완료",
    time: "3일 전",
    subject: "공통수학2",
    tags: ["고1", "내신"],
    grade: "고1",
    topicDistribution: [],
    variants: [],
    problems: [],
  },
  {
    id: "t4",
    title: "확률과 통계 단원 평가",
    problemCount: 20,
    status: "draft",
    statusText: "초안",
    time: "5일 전",
    subject: "확률과 통계",
    tags: ["고2", "단원평가"],
    grade: "고2",
    topicDistribution: [],
    variants: [],
    problems: [],
  },
  {
    id: "t5",
    title: "2024학년도 9월 모의평가",
    problemCount: 30,
    status: "ok",
    statusText: "완료",
    time: "1주 전",
    subject: "공통+미적분",
    tags: ["고3", "모의평가", "9월"],
    grade: "고3",
    topicDistribution: [],
    variants: [
      { id: "v2", createdAt: "2024-02-01", intensity: 2, count: 5 },
    ],
    problems: [],
  },
  {
    id: "t6",
    title: "기하 단원 정복",
    problemCount: 15,
    status: "ok",
    statusText: "완료",
    time: "2주 전",
    subject: "기하",
    tags: ["고3", "단원평가"],
    grade: "고3",
    topicDistribution: [],
    variants: [],
    problems: [],
  },
  {
    id: "t7",
    title: "중등 3학년 1학기 기말",
    problemCount: 25,
    status: "ok",
    statusText: "완료",
    time: "3주 전",
    subject: "중3",
    tags: ["중3", "내신"],
    grade: "중3",
    topicDistribution: [],
    variants: [],
    problems: [],
  },
  {
    id: "t8",
    title: "대수 단원 종합",
    problemCount: 18,
    status: "ok",
    statusText: "완료",
    time: "1개월 전",
    subject: "대수",
    tags: ["고2", "단원평가"],
    grade: "고2",
    topicDistribution: [],
    variants: [],
    problems: [],
  },
];
