import puppeteer from 'puppeteer-core';
import fs from 'node:fs/promises';
import { startBrowserFixture } from './browserFixture.mjs';
const fixture = await startBrowserFixture({ '/scripts/figureEditingHarnessEntry.tsx': 'scripts/figureEditingHarnessEntry.tsx' });
const browser = await puppeteer.launch({ executablePath: process.env.EDGE_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const checks=[];
const assert=(value,label)=>{if(!value)throw new Error(label);checks.push(label);console.log('PASS',label);};
try {
 const page=await browser.newPage();await page.setViewport({width:1500,height:1000});
 const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGEERROR',e.stack);});
  await page.goto(fixture.url,{waitUntil:'networkidle0'});
 await page.evaluate(async()=>{
   window.__detectCalls=0;
   const native=window.fetch;
   window.fetch=async(url,options)=>{
    if(url==='/api/ai-figure-labels') return Response.json({labels:JSON.parse(options.body).labels.map(()=>null)});
    if(url==='/api/ai-figure-detect'){
     window.__detectCalls++;
     const image=new Image();image.src=JSON.parse(options.body).questionCrop;await image.decode();
     return Response.json({figures:image.height>200?[{box:[250,90,790,400],label:'삼각형 A',kind:'diagram'},{box:[250,540,790,860],label:'삼각형 B',kind:'diagram'}]:[]});
    }
    return native(url,options);
   };
   const {mountEditingHarness}=await import('/scripts/figureEditingHarnessEntry.tsx');await mountEditingHarness('crop');
 });
 await page.waitForFunction(()=>document.querySelectorAll('[data-crop-kind="inner-figure"]').length===2);
 assert(await page.evaluate(()=>window.__detectCalls===2),'StrictMode detects each question once and shows two inner figures');
 assert(await page.$eval('[data-crop-kind="inner-figure"]',e=>getComputedStyle(e).borderColor)==='rgb(234, 88, 12)','Inner figure boxes use orange borders');
 await page.click('[data-crop-id="question-1"]');
 await page.click('[data-crop-kind="inner-figure"]');
 assert(await page.$eval('[data-crop-kind="inner-figure"]',e=>e.getAttribute('aria-pressed'))==='true','Inner figure remains selectable above its selected parent');
 const before=await page.evaluate(async()=>{const{s}= {s:(await import('/scripts/figureEditingHarnessEntry.tsx')).useWizardStore};return s.getState().pages[0].cropBoxes[0].figureCrops[0].bbox;});
 const target=await page.$('[data-crop-kind="inner-figure"]');const rect=await target.boundingBox();
 await page.mouse.move(rect.x+40,rect.y+40);await page.mouse.down();await page.mouse.move(rect.x+70,rect.y+55,{steps:5});await page.mouse.up();
 const after=await page.evaluate(async()=>{const{s}= {s:(await import('/scripts/figureEditingHarnessEntry.tsx')).useWizardStore};return s.getState().pages[0].cropBoxes[0].figureCrops[0].bbox;});
 assert(after[0]>before[0]&&after[1]>before[1],'Dragging an inner figure persists edited coordinates');
 await fs.mkdir('.checks.local',{recursive:true});await page.screenshot({path:'.checks.local/inner-figure-crop.png'});
 await page.evaluate(async()=>{const{mountEditingHarness}=await import('/scripts/figureEditingHarnessEntry.tsx');await mountEditingHarness('ocr');});
 assert(await page.$$eval('.choice-row .choice',els=>els.length===5&&new Set(els.map(e=>Math.round(e.getBoundingClientRect().x))).size===1),'Five answer choices follow the stored vertical layout');
 assert(await page.$$eval('[data-condition-box="1"] .grid > div',els=>els.length===3&&new Set(els.map(e=>Math.round(e.getBoundingClientRect().x))).size===1),'ㄱ, ㄴ, ㄷ items stay in one vertical column');
 await page.waitForSelector('[aria-label="그림 1 편집"]');await page.click('[aria-label="그림 1 편집"]');
 await page.waitForSelector('[aria-label="도형 1 편집기"]');
 assert(true,'Clicking the figure inside a problem opens its editor directly');
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="도형 1 편집기"] button')].find(b=>b.textContent.trim()==='취소').click());
 await page.waitForFunction(()=>!document.querySelector('[aria-label="도형 1 편집기"]'));
 await page.waitForSelector('[aria-label="문제 편집"]');await page.click('[aria-label="문제 편집"]');
 await page.waitForSelector('[aria-label="수식 삽입"]');
 assert(!await page.evaluate(()=>document.body.textContent.includes('미리보기')),'Problem editing uses one visual document instead of split source and preview panes');
 assert(await page.$$eval('.visual-document .choice-row .choice',els=>els.length===5&&new Set(els.map(e=>Math.round(e.getBoundingClientRect().x))).size===1),'Editor preserves the same vertical answer layout as the reader');
 assert(await page.$$eval('#editing-harness img',els=>els.some(e=>e.src.startsWith('data:image/svg'))),'Edit preview includes the diagram instead of a raw marker');
 await page.waitForSelector('[aria-label="문제 본문"]');
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="수식 삽입"] button')].find(b=>b.textContent==='분수').click());
 await page.waitForSelector('math-field[aria-label="수식 입력"]');
 await page.click('math-field[aria-label="수식 입력"]');
 await page.keyboard.down('Control');await page.keyboard.press('a');await page.keyboard.up('Control');
 await page.keyboard.type('2/3');
 await page.waitForFunction(()=>{const e=document.querySelector('math-field[aria-label="수식 입력"]');return e?.value?.includes('2')&&e.value.includes('3');});
 await page.keyboard.press('Escape');
 await page.waitForFunction(()=>{const e=document.querySelector('[aria-label="수식 편집"]');return e&&decodeURIComponent(e.dataset.mathTex||'').includes('2')&&decodeURIComponent(e.dataset.mathTex||'').includes('3');});
 assert(await page.$eval('[aria-label="수식 편집"]',e=>decodeURIComponent(e.dataset.mathTex).includes('2')&&decodeURIComponent(e.dataset.mathTex).includes('3')),'Fraction is edited in visual math form without typing LaTeX');
 await page.screenshot({path:'.checks.local/visual-question-editor.png'});
 await page.evaluate(()=>document.querySelector('[aria-label="그림 1 편집"]').click());
 await page.waitForSelector('[aria-label="도형 1 편집기"]');
 await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});
 await page.screenshot({path:'.checks.local/figure-editor-open.png'});
 assert(await page.$eval('#figure-editor-canvas',e=>Math.abs(e.getBoundingClientRect().width-e.querySelector('svg').getBoundingClientRect().width)<1),'Editor SVG fills its canvas without the document figure size cap');
 const listPlacement=await page.$eval('[aria-label="도형 요소 목록"]',e=>{const panel=e.parentElement.getBoundingClientRect(),list=e.getBoundingClientRect();return{bottom:Math.abs(panel.bottom-list.bottom),topRatio:(list.top-panel.top)/panel.height};});
 assert(listPlacement.bottom<2&&listPlacement.topRatio>.55,'Object list stays at the bottom below the detailed editor');
 await page.evaluate(()=>[...document.querySelectorAll('label')].find(e=>e.textContent.includes('원본을 흐리게 겹쳐 보기')).querySelector('input').click());
 await page.waitForSelector('[aria-label="겹쳐 보는 원본 크기"]');
 await page.$eval('[aria-label="겹쳐 보는 원본 크기"]',e=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'0.65');e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));});
 await page.waitForFunction(()=>document.querySelector('[alt="원본 겹쳐 보기"]')?.dataset.sourceOverlayScale==='0.65');
 assert(await page.$eval('[alt="원본 겹쳐 보기"]',e=>e.style.transform)==='scale(0.65)','Overlay source size changes immediately with the control below its toggle');
 await page.screenshot({path:'.checks.local/figure-overlay-scale.png'});
 const n=await page.$$eval('#figure-editor-canvas [data-object-id]',els=>els.length);
 assert(n===3,'Editor exposes line and text objects from engine SVG');
 const dragHandle=async(key,dx,dy)=>{
   await page.waitForSelector(`[data-figure-handle="${key}"]`);
   const handle=await page.$(`[data-figure-handle="${key}"]`);const box=await handle.boundingBox();
   await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();
   await page.mouse.move(box.x+box.width/2+dx,box.y+box.height/2+dy,{steps:12});await page.mouse.up();
 };
 const firstPath=await page.$('#figure-editor-canvas path');const firstPathBox=await firstPath.boundingBox();
 await page.mouse.click(firstPathBox.x+2,firstPathBox.y+2);
 await page.waitForSelector('[data-figure-handle="path-0-0"]');
 assert(await page.$$eval('[data-figure-handle]',els=>els.length)===3,'Triangle exposes three draggable vertices');
 const originalPath=await page.$eval('#figure-editor-canvas path',e=>e.getAttribute('d'));
 await dragHandle('path-0-0',45,25);
 assert((await page.$eval('#figure-editor-canvas path',e=>e.getAttribute('d')))!==originalPath,'Dragging a triangle vertex changes its shape without typing');
 await page.keyboard.down('Control');await page.keyboard.press('z');await page.keyboard.up('Control');
 assert((await page.$eval('#figure-editor-canvas path',e=>e.getAttribute('d')))===originalPath,'One undo restores an entire drag gesture');
 await page.click('#figure-editor-canvas text');await page.waitForSelector('[aria-label="선택한 도형 글자"]');
 await page.$eval('[aria-label="선택한 도형 글자"]',e=>e.select());await page.type('[aria-label="선택한 도형 글자"]','Z');
 assert(await page.$eval('#figure-editor-canvas text',e=>e.textContent)==='Z','Text labels can be edited directly');
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes('되돌리기')).click());
 assert(await page.$eval('#figure-editor-canvas text',e=>e.textContent)==='A','Undo restores the previous figure');
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes('다시 실행')).click());
 await page.click('#figure-editor-canvas text');
 await page.waitForSelector('[aria-label="선택한 도형 글자"]');
 assert(await page.$eval('[aria-label="선택한 도형 글자"]',e=>e.getBoundingClientRect().x)>await page.$eval('#figure-editor-canvas',e=>e.getBoundingClientRect().right),'Detailed label input is placed to the right of the canvas');
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="선택한 도형 글자 종류"] button')].find(b=>b.textContent.trim()==='수식').click());
 await page.waitForSelector('math-field[aria-label="선택한 도형 글자 수식"]');
 await page.$eval('math-field[aria-label="선택한 도형 글자 수식"]',e=>{e.value='v(t)';e.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>{const e=document.querySelector('#figure-editor-canvas text');return e?.textContent==='v(t)'&&e.getAttribute('data-mj')==='$v(t)$';});
 assert(await page.$eval('math-field[aria-label="선택한 도형 글자 수식"]',e=>e.value)==='v(t)','Figure math labels are edited visually without dollar-sign delimiters');
 assert(await page.$eval('#figure-editor-canvas text',e=>e.textContent)==='v(t)','Canvas never flashes raw math delimiters while a label is being typeset');
 await page.screenshot({path:'.checks.local/figure-label-math.png'});
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="선택한 도형 글자 종류"] button')].find(b=>b.textContent.trim()==='일반 글자').click());
 await page.waitForSelector('[aria-label="선택한 도형 글자"]');
 await page.$eval('[aria-label="선택한 도형 글자"]',e=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,'Z');e.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>document.querySelector('#figure-editor-canvas text')?.textContent==='Z');
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="도형 편집 도구"] button')].find(b=>b.textContent.trim()==='○원').click());
 const surface=await page.$('#figure-editor-canvas');const area=await surface.boundingBox();
 await page.mouse.move(area.x+350,area.y+250);await page.mouse.down();await page.mouse.move(area.x+395,area.y+295,{steps:4});await page.mouse.up();
 assert(await page.$$eval('#figure-editor-canvas circle',els=>els.length)===1,'Users can draw a new circle on the vector canvas');
 await page.waitForSelector('[data-figure-handle="radius-0"]');
 const beforeRadius=await page.$eval('#figure-editor-canvas circle',e=>+e.getAttribute('r'));
 await dragHandle('radius-0',35,0);
 assert(await page.$eval('#figure-editor-canvas circle',e=>+e.getAttribute('r'))>beforeRadius,'Circle radius changes by dragging its rim handle');
 const beforeCenter=await page.$eval('#figure-editor-canvas circle',e=>+e.getAttribute('cy'));
 await dragHandle('center',0,25);
 assert(await page.$eval('#figure-editor-canvas circle',e=>+e.getAttribute('cy'))>beforeCenter,'Circle center moves with its center handle');
 await page.evaluate(()=>[...document.querySelectorAll('label')].find(l=>l.textContent==='점선').querySelector('input').click());
 assert(await page.$eval('#figure-editor-canvas circle',e=>e.getAttribute('stroke-dasharray'))==='5 4','Selected objects support dashed strokes');
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="도형 편집 도구"] button')].find(b=>b.textContent==='삭제').click());
 assert(await page.$$eval('#figure-editor-canvas circle',els=>els.length)===0,'Delete removes only the selected object');
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes('되돌리기')).click());
 await page.screenshot({path:'.checks.local/figure-editor.png'});
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='도형 적용').click());
 await page.waitForFunction(()=>!document.querySelector('[aria-label="도형 1 편집기"]'));
 await page.evaluate(()=>[...document.querySelectorAll('#editing-harness button')].find(b=>b.textContent.trim()==='저장').click());
 assert(await page.evaluate(async()=>{const{s}= {s:(await import('/scripts/figureEditingHarnessEntry.tsx')).useWizardStore};const item=s.getState().pages[0].ocrResult[0];return item.images[0].engineSvg.includes('>Z</text>')&&item.images[0].engineSvg.includes('<circle')&&item.text.includes('\\frac23')&&item.text.includes('> <보기>')&&!item.text.includes('**<보기>**');}),'Applying and saving preserves visual math, condition markup, and edited SVG in the question');
 await page.evaluate(async()=>{
   const {mountDirectFigure}=await import('/scripts/figureEditingHarnessEntry.tsx');
   mountDirectFigure('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 360"><g transform="translate(15 10) scale(1.1)"><line id="drag-line" x1="30" y1="65" x2="170" y2="65" stroke="black" stroke-width="1"/><path id="drag-curve" d="M 220 140 Q 285 40 350 140" fill="none" stroke="black" stroke-width="2"/><polygon id="drag-polygon" points="230,210 280,285 350,240" fill="none" stroke="black" stroke-width="2"/><rect id="drag-rect" x="30" y="205" width="120" height="70" fill="none" stroke="black" stroke-width="2"/><ellipse id="drag-ellipse" cx="90" cy="135" rx="40" ry="24" fill="none" stroke="black" stroke-width="2"/><path id="drag-arc" d="M 320 65 A 28 28 0 0 1 375 65" fill="none" stroke="black" stroke-width="2"/></g></svg>');
 });
 await page.waitForSelector('#drag-line');
 await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});
 const location=async(selector,x,y)=>page.$eval(selector,(e,{x,y})=>{const m=e.getScreenCTM();const p=new DOMPoint(x,y).matrixTransform(m);return{x:p.x,y:p.y,scale:Math.hypot(m.a,m.b)};},{x,y});
 let pos=await location('#drag-line',90,65);
 await page.mouse.click(pos.x,pos.y+6);
 await page.waitForSelector('[data-figure-handle="end"]');
 assert(true,'Thin lines can be selected six pixels away from the stroke');
 await dragHandle('end',45,24);
 const endpoint=await page.$eval('#drag-line',e=>({x:+e.getAttribute('x2'),y:+e.getAttribute('y2')}));
 assert(Math.abs(endpoint.x-(170+45/pos.scale))<1&&Math.abs(endpoint.y-(65+24/pos.scale))<1,'Line endpoint follows the mouse inside a transformed group');
 await page.click('[aria-label="도형 확대"]');await page.click('[aria-label="도형 확대"]');
 pos=await location('#drag-line',+endpoint.x,+endpoint.y);
 await dragHandle('end',24,0);
 assert(Math.abs((await page.$eval('#drag-line',e=>+e.getAttribute('x2')))-endpoint.x-24/pos.scale)<1,'Endpoint dragging stays accurate after zooming');
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='맞춤').click());
 pos=await location('#drag-curve',285,90);await page.mouse.click(pos.x,pos.y);
 await page.waitForSelector('[data-figure-handle="path-1-0"]');
 await dragHandle('path-1-0',0,-40);
 const curve=await page.$eval('#drag-curve',e=>e.getAttribute('d').match(/-?(?:\d*\.)?\d+/g).map(Number));
 assert(curve[0]===220&&curve[1]===140&&curve[3]<40&&curve[4]===350&&curve[5]===140,'Dragging a curve control changes curvature while keeping both endpoints');
 await page.screenshot({path:'.checks.local/figure-mouse-curve.png'});
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='다각형 3').click());
 await page.waitForSelector('[data-figure-handle="point-0"]');
 await new Promise(resolve=>setTimeout(resolve,450));
 await dragHandle('point-0',-25,-15);
 const polygon=await page.$eval('#drag-polygon',e=>e.getAttribute('points').split(/[ ,]+/).map(Number));
 assert(polygon[0]<230&&polygon[1]<210&&polygon[2]===280&&polygon[3]===285,'Polygon vertex moves independently without changing other vertices');
 pos=await location('#drag-rect',90,205);await page.mouse.click(pos.x,pos.y);
 await page.waitForSelector('[data-figure-handle="corner-2"]');
 await dragHandle('corner-2',30,20);
 assert(await page.$eval('#drag-rect',e=>+e.getAttribute('width')>120&&+e.getAttribute('height')>70&&+e.getAttribute('x')===30&&+e.getAttribute('y')===205),'Rectangle corner resizes naturally around the opposite corner');
 pos=await location('#drag-ellipse',130,135);await page.mouse.click(pos.x,pos.y);
 await page.waitForSelector('[data-figure-handle="radius-0"]');
 await dragHandle('radius-0',25,0);
 assert(await page.$eval('#drag-ellipse',e=>+e.getAttribute('rx')>40&&+e.getAttribute('ry')===24),'Ellipse width changes without disturbing its height');
 // Arc commands keep their geometry and get a bounding-box resize fallback.
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='곡선/경로 6').click());
 await page.waitForSelector('[data-figure-handle="resize-2"]');
 await dragHandle('resize-2',25,15);
 assert(await page.$eval('#drag-arc',e=>e.getAttribute('d').includes('A 28 28')&&e.getAttribute('transform').includes('scale(')),'Complex paths resize by mouse without rewriting their geometry');
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="도형 편집 도구"] button')].find(b=>b.textContent.includes('화면 이동')).click());
 for(let i=0;i<6;i++)await page.click('[aria-label="도형 확대"]');
 const v=await page.$eval('[aria-label="도형 편집 캔버스"]',e=>{const p=e.parentElement,r=p.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};});
 await page.mouse.move(v.x,v.y);await page.mouse.down();await page.mouse.move(v.x-80,v.y-65,{steps:8});await page.mouse.up();
 assert(await page.$eval('[aria-label="도형 편집 캔버스"]',e=>e.parentElement.scrollLeft>30&&e.parentElement.scrollTop>30),'Hand tool pans an enlarged drawing by dragging');
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='맞춤').click());
 await page.setViewport({width:1024,height:768});
 await page.waitForFunction(()=>{const e=document.querySelector('[aria-label="도형 편집 캔버스"]');return e.getBoundingClientRect().width<=e.parentElement.clientWidth-40;});
 assert(true,'Fit view keeps the entire drawing visible on a smaller screen');
 await page.setViewport({width:1500,height:1000});
 await page.evaluate(()=>[...document.querySelectorAll('[aria-label="도형 편집 도구"] button')].find(b=>b.textContent.includes('선택·이동')).click());
 await page.screenshot({path:'.checks.local/figure-mouse-editor.png'});
 await page.evaluate(()=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='도형 적용').click());
 await page.waitForFunction(()=>!document.querySelector('[aria-label="도형 1 편집기"]'));
 assert(await page.evaluate(async()=>{const svg=(await import('/scripts/figureEditingHarnessEntry.tsx')).getSavedFigure();return svg.includes('drag-curve')&&!svg.includes('data-figure-handle')&&!svg.includes('data-object-id');}),'Mouse edits save clean geometry without selection handles or editor artifacts');
 await page.evaluate(async()=>{const{mountRendererRegression}=await import('/scripts/figureEditingHarnessEntry.tsx');mountRendererRegression('구간 $[a,b]$에서 $x(b)=-8-x(b) \\implies x(b)=-4$. <span data-katex-id="10"></span> 따라서 거리는 $8$이다.');});
 await page.waitForSelector('#editing-harness .katex');
 assert(await page.$eval('#editing-harness',e=>!e.textContent.includes('data-katex')&&!e.textContent.includes('<span')),'Solution rendering never exposes internal KaTeX placeholder tags');
 assert(await page.$$eval('#editing-harness .katex-error',els=>els.length===0),'Solution post-processing leaves no KaTeX error fallback');
 assert(errors.length===0,'No browser runtime errors');
 console.log(`${checks.length} editing checks passed`);
}finally{await browser.close(); await fixture.close();}
