import puppeteer from 'puppeteer-core';
import fs from 'node:fs/promises';
import { startBrowserFixture } from './browserFixture.mjs';

const entry='/scripts/navigationHarnessEntry.tsx';
const fixture=await startBrowserFixture({[entry]:'scripts/navigationHarnessEntry.tsx'});
const browser=await puppeteer.launch({executablePath:process.env.EDGE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
let count=0;
const assert=(value,message)=>{if(!value)throw new Error(message);console.log('PASS',message);count++;};
try {
  const page=await browser.newPage();await page.setViewport({width:1500,height:1000});
  const errors=[];page.on('pageerror',error=>{errors.push(error.message);console.log('PAGEERROR',error.message);});
  page.on('dialog',dialog=>dialog.accept());
  await page.goto(fixture.url);
  const mount=async(auth=false)=>page.evaluate(async({entry,auth})=>{const h=await import(entry);h.mountNavigation(auth);},{entry,auth});
  const state=()=>page.evaluate(async(entry)=>{const h=await import(entry);const a=h.useAppStore.getState(),w=h.useWizardStore.getState();return {screen:a.screen,testId:a.selectedTestId,tab:a.detailTab,detailPage:a.detailPage,route:a.route,mode:a.authMode,step:w.step,furthest:w.furthestStep,skip:w.skipSolutions,pages:w.pages.length};},entry);
  const action=async(fn)=>page.evaluate(async({entry,fn})=>{const h=await import(entry);return new Function('h',fn)(h);},{entry,fn});
  const step=async(n)=>page.waitForFunction(async({entry,n})=>(await import(entry)).useWizardStore.getState().step===n,{}, {entry,n});
  const button=async(text)=>page.evaluate(text=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text&&!b.disabled);if(!b)throw new Error('Missing button: '+text);b.click();},text);
  const back=async()=>{await page.goBack();await new Promise(resolve=>setTimeout(resolve,80));};
  const forward=async()=>{await page.goForward();await new Promise(resolve=>setTimeout(resolve,80));};
  await mount();
  await page.waitForFunction(()=>document.body.textContent.includes('2024학년도 6월 모의평가'));
  await action('h.useLibraryStore.getState().setViewState({searchQuery:"2024"});');
  await page.evaluate(()=>[...document.querySelectorAll('h3,div')].filter(e=>e.textContent==='2024학년도 6월 모의평가').at(-1).click());
  await page.waitForSelector('[role="tablist"]');
  assert((await state()).screen==='detail'&&page.url().includes('test=t1'),'Opening a test records the detail URL');
  await page.click('[role="tab"]:nth-child(2)');
  assert((await state()).tab==='solutions','Solution tab is navigable');
  await back();assert((await state()).tab==='problems','Browser Back restores the previous detail tab');
  await back();assert((await state()).screen==='library','Browser Back restores the library');
  assert(await action('return h.useLibraryStore.getState().viewState.searchQuery;')==='2024','Returning to library preserves its search filter');
  await forward();await forward();assert((await state()).tab==='solutions','Browser Forward restores detail and its selected tab');
  await page.reload();await mount();await page.waitForSelector('[role="tablist"]');
  assert((await state()).screen==='detail'&&(await state()).tab==='solutions','Reload rehydrates a directly linked detail and tab');
  await action('h.useAppStore.getState().setDetailPage(2);');await back();assert((await state()).detailPage===1,'Detail page selection participates in browser history');
  await action('h.useAppStore.getState().backToLibrary();');
  await action('return h.seedWizard();');await page.waitForSelector('[aria-label="위자드 종료"]');
  for(let n=1;n<=6;n++){
    const texts=['','저장','모든 페이지 검토 완료','모든 문항 확인 완료','저장','저장','저장'];
    await button(texts[n]);await step(n);
    assert(new URL(page.url()).searchParams.get('step')===String(n+1),`Wizard Next records step ${n+1}`);
  }
  const beforeLength=await page.evaluate(()=>history.length);
  for(let n=5;n>=0;n--){await back();await step(n);}
  assert((await state()).furthest===6,'Browser Back across all seven steps preserves completed progress');
  for(let n=1;n<=6;n++){await forward();await step(n);}
  assert(await page.evaluate(()=>history.length)===beforeLength,'Back and Forward never duplicate history entries');
  await button('이전 (검토)');await step(5);
  assert(true,'Export Previous returns to review');
  const imageRef=await action('return h.useWizardStore.getState().pages[0].imageRef;');
  await page.click('[aria-label="위자드 종료"]');assert((await state()).screen==='library','Wizard Exit returns to library');
  await back();await page.waitForSelector('[aria-label="위자드 종료"]');
  assert((await state()).pages===1&&!await page.$('[aria-label="이전 변환 작업 발견"]'),'Returning after Exit preserves work without an extra resume dialog');
  assert(await page.evaluate(async({entry,imageRef})=>!!await(await import(entry)).getPageImage(imageRef),{entry,imageRef}),'Exit preserves source images in IndexedDB');
  await page.click('[aria-label="3단계 OCR"]');await step(2);await button('해설 건너뛰기');await step(4);
  await back();await step(2);await forward();await step(4);
  await button('이전');await step(2);assert((await state()).skip,'Skipped solutions stay skipped during browser and button navigation');
  await action('h.useWizardStore.getState().setStep(4);');await step(4);
  await page.reload();await mount();await page.waitForSelector('[aria-label="위자드 종료"]');
  assert((await state()).step===4&&(await state()).pages===1,'Wizard reload restores the URL step and saved data');
  if(await page.$('[aria-label="이전 변환 작업 발견"]'))await button('이어하기');
  await action('h.useAppStore.getState().backToLibrary();h.useAppStore.getState().setRoute("admin");');
  await page.waitForFunction(()=>document.body.textContent.includes('로그인이 필요합니다'));
  assert((await state()).route==='admin','Admin navigation still enforces its access gate');
  await action('h.useAdminStore.getState().setSection("errors");');await back();
  assert(await action('return h.useAdminStore.getState().section;')==='usage','Admin sections restore on browser Back');
  await back();assert((await state()).route==='app','Browser Back exits admin without a full reload');
  await forward();assert((await state()).route==='admin','Browser Forward reopens admin');
  await action('h.useAppStore.getState().backToLibrary();');await mount(true);
  await button('회원가입');assert((await state()).mode==='signup','Signup is recorded in history');
  await back();assert((await state()).mode==='login','Browser Back restores login');
  await forward();assert((await state()).mode==='signup','Browser Forward restores signup');
  await action('h.useAppStore.getState().setAuthMode("reset");');await back();assert((await state()).mode==='signup','Password reset does not trap browser Back');
  await action('h.useAppStore.getState().backToLibrary();h.useAppStore.getState().setAuthMode("login");');await mount();
  await action('h.useAppStore.getState().openModal("new-variant");');await back();
  assert(await action('return h.useAppStore.getState().modal;')===null,'Browser Back closes the new-test dialog');
  await forward();assert(await action('return h.useAppStore.getState().modal;')==='new-variant','Browser Forward restores the new-test dialog');
  await page.goto(`${fixture.url}/?screen=wizard&test=another-test&step=7`);await mount();
  assert((await state()).screen==='detail'&&(await state()).testId==='another-test','A stale wizard link opens its saved detail instead of overwriting the active work');
  assert((await state()).pages===1,'Stale links preserve the existing wizard pages');
  await page.goto(`${fixture.url}/?screen=wizard&test=t1&step=99`);await mount();
  assert((await state()).step===6&&new URL(page.url()).searchParams.get('step')==='7','Out-of-range wizard links clamp to completed progress');
  await page.goto(`${fixture.url}/?screen=detail&test=t1&tab=invalid&page=-5&search=admin`);await mount();
  assert((await state()).route==='app'&&(await state()).tab==='problems'&&(await state()).detailPage===1,'Invalid detail routes normalize without matching query values as routes');
  assert(errors.length===0,'No browser runtime errors during navigation');
  await fs.mkdir('.checks.local',{recursive:true});await page.screenshot({path:'.checks.local/navigation.png'});
  console.log(`${count} navigation checks passed`);
} finally {await browser.close();await fixture.close();}
